### ISSUE TITLE
Need thumbnail pics for the Urdu and Chinese Projects

### ISSUE THREAD

**Issue by ndalyrose** [LibCrowds/project-convert-a-card#6]
Missing pics here for the Urdu and Chinese Projects. https://www.libcrowds.com/collection/convertacard/contribute/

**Comment by ndalyrose** [comment]
Moving to under vue pybossa front-end :)

**Comment by alexandermendes** [comment]
Cool, here would've been fine too! Just keeping them all in the other one as it should be a bit easier to manage (directing people to the various repos proved confusing)!
